version: "3.6"
services:
  ###### Postgres DB
  postgres:
    image: postgres:14.3
    ports:
      - "5500:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: irembo_db
      
  #### Postgres Admin View
  postgres_admin:
    image: dpage/pgadmin4:6
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pass
    ports:
      - "9000:80"
        
  ########### Spring Boot Eureka Server
  eureka-server:
    container_name: eureka_server_service
    image: eureka_server_image
    build:
      dockerfile: Dockerfile
      context: ../discovery-server
    ports:
      - "8760:8760"

  ########## Spring Boot Config Server
  config-server:
    container_name: config_server_service
    image: config_server_image
    build:
      dockerfile: Dockerfile
      context: ../config-server
    depends_on:
      - eureka-server
    environment:
      EUREKA_DEFAULT_ZONE: http://eureka-server:8760/eureka
    ports:
      - "9090:9090"

  ########## Spring Boot Api Gateway
  api-gateway:
    container_name: api_gateway_service
    image: api_gateway_image
    build:
      dockerfile: Dockerfile
      context: ../api-gateway
    depends_on:
      - config-server
    environment:
      EUREKA_DEFAULT_ZONE: http://eureka-server:8760/eureka
      CONFIG_SERVER_ZONE: http://config-server:9090
    ports:
      - "9090:9090"
      
  ########### Spring Boot Main Service
  irembo-app:
    container_name: irembo_back_service
    image: irembo_back_image
    build:
      dockerfile: Dockerfile
      context: ../irembo-back
    depends_on:
      - postgres
      - eureka-server
      - config-server
      - email-app
    environment:
      DATABASE_URL: postgresql://postgres:5432/irembo_db
      DATABASE_USER: user
      DATABASE_PASSWORD: pass
      EUREKA_DEFAULT_ZONE: http://eureka-server:8760/eureka
      CONFIG_SERVER_ZONE: http://config-server:9090
    ports:
      - "8090:8090"
      
  ########### Spring Boot Email Service
  email-app:
    container_name: email_app_service
    image: email_app_image
    build:
      dockerfile: Dockerfile
      context: ../email-microservice
    depends_on:
      - eureka-server
      - config-server
    environment:
      EUREKA_DEFAULT_ZONE: http://eureka-server:8760/eureka
      CONFIG_SERVER_ZONE: http://config-server:9090
    ports:
      - "30:30"